### ISSUE TITLE
Использование параметра --yandex-userdata не позволяет docker-machine получать ssh ключи доступа

### ISSUE THREAD

**Issue by Shikaka** [yandex-cloud/docker-machine-driver-yandex#6]
Разбираюсь с поведением параметра --yandex-userdata

**Что хочу получить:**
На создаваемой машине необходимо добавить несколько строчек в hosts.
С виду параметр `--yandex-userdata` подходит для этой цели, чтобы передать дополнительные настройки cloud-init

**Что делаю:**
Создаю файл /tmp/custom-userdata.yml
```
#cloud-config
runcmd:
  - echo Test runcmd
  - echo 127.0.0.1 myservice >> /etc/hosts
```
добавляю параметр `--yandex-userdata=/tmp/custom-userdata.yml`
полная команда выглядит так:
```
docker-machine --debug create -d yandex \
--yandex-cloud-id=*** \
--yandex-folder-id=*** \
--yandex-subnet-id=*** \
--yandex-token=*** \
--yandex-ssh-user=*** \
--yandex-cores=1 \
--yandex-disk-size=20 \
--yandex-disk-type=network-hdd \
--yandex-memory=2 \
--yandex-use-internal-ip=1 \
--yandex-nat=0 \
--yandex-userdata=/tmp/custom-userdata.yml \
 foo
```

**Что ожидаю:**
Создания ВМ с сообщением "Test runcmd" в логах создания и изменненым hosts

**Что получаю:**
"зависание" на ожидании ssh-ключа доступа
```
(foo) Creating instance...
(foo) Use image with ID "fd8fjtn3mj2kfe7h6f0r" from folder ID "standard-images"
(foo) Waiting for Instance with ID "fhmk77og2809r847lui1"
(foo) Calling .GetConfigRaw
(foo) Calling .DriverName
(foo) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(foo) Calling .GetState
(foo) DBG | Instance State: RUNNING
Detecting operating system of created instance...
Waiting for SSH to be available...
Getting to WaitForSSH function...
(foo) Calling .GetSSHHostname
(foo) Calling .GetSSHPort
(foo) Calling .GetSSHKeyPath
(foo) Calling .GetSSHKeyPath
(foo) Calling .GetSSHUsername
Using SSH client type: external
<nil>
Error getting ssh command 'exit 0' : stat /root/.docker/machine/machines/foo/id_rsa: no such file or directory
Getting to WaitForSSH function...
(foo) Calling .GetSSHHostname
(foo) Calling .GetSSHPort
(foo) Calling .GetSSHKeyPath
(foo) Calling .GetSSHKeyPath
(foo) Calling .GetSSHUsername
Using SSH client type: external
<nil>
Error getting ssh command 'exit 0' : stat /root/.docker/machine/machines/foo/id_rsa: no such file or directory
Getting to WaitForSSH function...
```

Посмотрел код и понял, что user-data используется самим драйвером для добавления сгенерированного ключа доступа и настроек пользователя.
Если же передавать свои user-data, то не происходит генерации ключей доступа docker-mashine к ВМ и установка не завершается успешно.

**Что еще пробовал сделать:**
Использовать заранее сгененированный ключ для доступа
custom-userdata.yml
```
#cloud-config
ssh_pwauth: no

users:
  - name: ***
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3Nza...

runcmd:
  - echo Test runcmd
  - echo 127.0.0.1 myservice >> /etc/hosts
```
- Это работает если во время создания руками подложить ключ в каталог машины
`cp ~/.ssh/id_rsa ~/.docker/machine/machines/foo/id_rsa` 

После такого изменения ВМ создается с ожидаемыми параметрами и сообщениями

**Что предлагаю:**
Предлагаю несколько вариантов улучшения:
- мержить передаваемую user-data и необходимую для работы драйвера 
- добавить возможность передавать приватную часть ключа, для использования в драйвере (так в openstack реализовано например)

**Comment by GennadySpb** [comment]
Привет @Shikaka !

Теперь должно работать для любой ОС.

**Comment by GennadySpb** [comment]
@Shikaka удалось проверить?

**Comment by Shikaka** [comment]
Работает с конфигом вида
```
#cloud-config
runcmd:
  - echo Test runcmd
  - echo 127.0.0.1 myservice >> /etc/hosts
```

Если пытаться задавать дополнительные ключи доступа или пользователей, то не работает
Пример не работающего конфига (--yandex-ssh-user=ubuntu):
```
#cloud-config
ssh_pwauth: no

users:
  - name: developer
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3Nza...

runcmd:
  - echo Test runcmd
  - echo 127.0.0.1 myservice >> /etc/hosts
```
Однако думаю, что желание создавать других пользователей на хосте, заточенном под выполнение докер контейнеров, само по себе странно.

Для моих целей текущего решения достаточно. Спасибо.
